{
	"Architecture": [
		"all"
	],
	"Binary": [
		"python-debianbts"
	],
	"Build-Depends": [
		"dpatch, debhelper (>= 7), python-support (>= 0.6)"
	],
	"Checksums-Sha1": [
		"a2155080a6f54cc79869f96cf03e792310932e6e 818 python-debianbts_0.2.1.dsc 3c4c578637bdf0de603c933ec4375c2db828ba27 7640 python-debianbts_0.2.1.tar.gz"
	],
	"Checksums-Sha256": [
		"4056cdf59b119e20147e1019e7d7cb92360fc50b053ef8404597363cef9d599d 818 python-debianbts_0.2.1.dsc 1dea5a2693fd06589f677d3ae961c02d2e32851777e87897fc4674a123e7b4ec 7640 python-debianbts_0.2.1.tar.gz"
	],
	"Directory": [
		"pool/main/p/python-debianbts"
	],
	"Files": [
		"6ca8973f91d4b4af00826a3b0641268d 818 python-debianbts_0.2.1.dsc f753ec9c0ca96e95a14d51e6e737cffa 7640 python-debianbts_0.2.1.tar.gz"
	],
	"Format": [
		"1.0"
	],
	"Homepage": [
		"http://reportbug-ng.alioth.debian.org"
	],
	"Maintainer": [
		"Bastian Venthur <venthur@debian.org>"
	],
	"Package": [
		"python-debianbts"
	],
	"Priority": [
		"extra"
	],
	"Section": [
		"python"
	],
	"Standards-Version": [
		"3.8.0"
	],
	"Version": [
		"0.2.1"
	]
}
