{
	"header": {
		"line": "CVE-2023-6597 (An issue was found in the CPython `tempfile.TemporaryDirectory` class  ...)",
		"name": "CVE-2023-6597",
		"description": "(An issue was found in the CPython `tempfile.TemporaryDirectory` class  ...)"
	},
	"annotations": [
		{
			"line": "\t{DLA-3772-1}",
			"type": "xref",
			"bugs": [
				"DLA-3772-1"
			]
		},
		{
			"line": "\t- python3.12 3.12.1-1",
			"type": "package",
			"package": "python3.12",
			"kind": "fixed",
			"version": "3.12.1-1"
		},
		{
			"line": "\t- python3.11 3.11.8-1",
			"type": "package",
			"package": "python3.11",
			"kind": "fixed",
			"version": "3.11.8-1"
		},
		{
			"line": "\t- python3.10 <unfixed>",
			"type": "package",
			"package": "python3.10",
			"kind": "unfixed"
		},
		{
			"line": "\t- python3.9 <removed>",
			"type": "package",
			"package": "python3.9",
			"kind": "removed"
		},
		{
			"line": "\t- python3.7 <removed>",
			"type": "package",
			"package": "python3.7",
			"kind": "removed"
		},
		{
			"line": "\t- python2.7 <not-affected> (tempfile.TemporaryDirectory added in 3.2)",
			"type": "package",
			"package": "python2.7",
			"kind": "not-affected",
			"description": "tempfile.TemporaryDirectory added in 3.2"
		},
		{
			"line": "\tNOTE: https://github.com/python/cpython/pull/99930",
			"type": "NOTE",
			"description": "https://github.com/python/cpython/pull/99930"
		},
		{
			"line": "\tNOTE: https://github.com/python/cpython/issues/91133",
			"type": "NOTE",
			"description": "https://github.com/python/cpython/issues/91133"
		},
		{
			"line": "\tNOTE: https://github.com/python/cpython/commit/6ceb8aeda504b079fef7a57b8d81472f15cdd9a5 (v3.12.1)",
			"type": "NOTE",
			"description": "https://github.com/python/cpython/commit/6ceb8aeda504b079fef7a57b8d81472f15cdd9a5 (v3.12.1)"
		},
		{
			"line": "\tNOTE: https://github.com/python/cpython/commit/5585334d772b253a01a6730e8202ffb1607c3d25 (v3.11.8)",
			"type": "NOTE",
			"description": "https://github.com/python/cpython/commit/5585334d772b253a01a6730e8202ffb1607c3d25 (v3.11.8)"
		},
		{
			"line": "\tNOTE: https://github.com/python/cpython/commit/8eaeefe49d179ca4908d052745e3bb8b6f238f82 (v3.10.14)",
			"type": "NOTE",
			"description": "https://github.com/python/cpython/commit/8eaeefe49d179ca4908d052745e3bb8b6f238f82 (v3.10.14)"
		},
		{
			"line": "\tNOTE: https://github.com/python/cpython/commit/d54e22a669ae6e987199bb5d2c69bb5a46b0083b (v3.9.19)",
			"type": "NOTE",
			"description": "https://github.com/python/cpython/commit/d54e22a669ae6e987199bb5d2c69bb5a46b0083b (v3.9.19)"
		},
		{
			"line": "\tNOTE: https://mail.python.org/archives/list/security-announce@python.org/thread/Q5C6ATFC67K53XFV4KE45325S7NS62LD/",
			"type": "NOTE",
			"description": "https://mail.python.org/archives/list/security-announce@python.org/thread/Q5C6ATFC67K53XFV4KE45325S7NS62LD/"
		}
	]
}
