{
	"header": {
		"line": "CVE-2023-46045 (Graphviz 2.36.0 through 9.x before 10.0.1 has an out-of-bounds read vi ...)",
		"name": "CVE-2023-46045",
		"description": "(Graphviz 2.36.0 through 9.x before 10.0.1 has an out-of-bounds read vi ...)"
	},
	"annotations": [
		{
			"line": "\t- graphviz 2.42.2-8 (unimportant)",
			"type": "package",
			"package": "graphviz",
			"kind": "fixed",
			"version": "2.42.2-8",
			"flags": [
				{
					"severity": "unimportant"
				}
			]
		},
		{
			"line": "\tNOTE: Crosses no security boundary, config files are under local control",
			"type": "NOTE",
			"description": "Crosses no security boundary, config files are under local control"
		},
		{
			"line": "\tNOTE: https://gitlab.com/graphviz/graphviz/-/issues/2441",
			"type": "NOTE",
			"description": "https://gitlab.com/graphviz/graphviz/-/issues/2441"
		},
		{
			"line": "\tNOTE: Introduced by: https://gitlab.com/graphviz/graphviz/-/commit/cf95714837f06f684929b54659523c2c9b1fc19f (2.38.0)",
			"type": "NOTE",
			"description": "Introduced by: https://gitlab.com/graphviz/graphviz/-/commit/cf95714837f06f684929b54659523c2c9b1fc19f (2.38.0)"
		},
		{
			"line": "\tNOTE: Fixed by: https://gitlab.com/graphviz/graphviz/-/commit/361f274ca901c3c476697a6404662d95f4dd43cb",
			"type": "NOTE",
			"description": "Fixed by: https://gitlab.com/graphviz/graphviz/-/commit/361f274ca901c3c476697a6404662d95f4dd43cb"
		},
		{
			"line": "\tNOTE: Fixed by: https://gitlab.com/graphviz/graphviz/-/commit/3f31704cafd7da3e86bb2861accf5e90c973e62a",
			"type": "NOTE",
			"description": "Fixed by: https://gitlab.com/graphviz/graphviz/-/commit/3f31704cafd7da3e86bb2861accf5e90c973e62a"
		},
		{
			"line": "\tNOTE: Fixed by: https://gitlab.com/graphviz/graphviz/-/commit/a95f977f5d809915ec4b14836d2b5b7f5e74881e",
			"type": "NOTE",
			"description": "Fixed by: https://gitlab.com/graphviz/graphviz/-/commit/a95f977f5d809915ec4b14836d2b5b7f5e74881e"
		}
	]
}
