{
	"header": {
		"line": "CVE-2023-6110 (A flaw was found in OpenStack. When a user tries to delete a non-exist ...)",
		"name": "CVE-2023-6110",
		"description": "(A flaw was found in OpenStack. When a user tries to delete a non-exist ...)"
	},
	"annotations": [
		{
			"line": "\t- python-openstackclient 6.3.0-2",
			"type": "package",
			"package": "python-openstackclient",
			"kind": "fixed",
			"version": "6.3.0-2"
		},
		{
			"line": "\t[bookworm] - python-openstackclient <no-dsa> (Minor issue)",
			"type": "package",
			"release": "bookworm",
			"package": "python-openstackclient",
			"kind": "no-dsa",
			"description": "Minor issue"
		},
		{
			"line": "\t[bullseye] - python-openstackclient <no-dsa> (Minor issue)",
			"type": "package",
			"release": "bullseye",
			"package": "python-openstackclient",
			"kind": "no-dsa",
			"description": "Minor issue"
		},
		{
			"line": "\t[buster] - python-openstackclient <not-affected> (app cred access rules introduced in v5)",
			"type": "package",
			"release": "buster",
			"package": "python-openstackclient",
			"kind": "not-affected",
			"description": "app cred access rules introduced in v5"
		},
		{
			"line": "\tNOTE: https://bugzilla.redhat.com/show_bug.cgi?id=2212960",
			"type": "NOTE",
			"description": "https://bugzilla.redhat.com/show_bug.cgi?id=2212960"
		},
		{
			"line": "\tNOTE: https://bugzilla.redhat.com/show_bug.cgi?id=2209607",
			"type": "NOTE",
			"description": "https://bugzilla.redhat.com/show_bug.cgi?id=2209607"
		},
		{
			"line": "\tNOTE: https://review.opendev.org/888697",
			"type": "NOTE",
			"description": "https://review.opendev.org/888697"
		}
	]
}
