{
	"header": {
		"line": "CVE-2014-4616 (Array index error in the scanstring function in the _json module in Py ...)",
		"name": "CVE-2014-4616",
		"description": "(Array index error in the scanstring function in the _json module in Py ...)"
	},
	"annotations": [
		{
			"line": "\t- python2.5 <removed>",
			"type": "package",
			"package": "python2.5",
			"kind": "removed"
		},
		{
			"line": "\t[squeeze] - python2.5 <no-dsa> (minor issue)",
			"type": "package",
			"release": "squeeze",
			"package": "python2.5",
			"kind": "no-dsa",
			"description": "minor issue"
		},
		{
			"line": "\t- python2.6 <removed>",
			"type": "package",
			"package": "python2.6",
			"kind": "removed"
		},
		{
			"line": "\t[squeeze] - python2.6 <no-dsa> (minor issue)",
			"type": "package",
			"release": "squeeze",
			"package": "python2.6",
			"kind": "no-dsa",
			"description": "minor issue"
		},
		{
			"line": "\t[wheezy] - python2.6 <no-dsa> (minor issue)",
			"type": "package",
			"release": "wheezy",
			"package": "python2.6",
			"kind": "no-dsa",
			"description": "minor issue"
		},
		{
			"line": "\t- python2.7 2.7.7-1 (bug #752395)",
			"type": "package",
			"package": "python2.7",
			"kind": "fixed",
			"version": "2.7.7-1",
			"flags": [
				{
					"bug": 752395
				}
			]
		},
		{
			"line": "\t[wheezy] - python2.7 <no-dsa> (minor issue)",
			"type": "package",
			"release": "wheezy",
			"package": "python2.7",
			"kind": "no-dsa",
			"description": "minor issue"
		},
		{
			"line": "\t- python3.2 <removed>",
			"type": "package",
			"package": "python3.2",
			"kind": "removed"
		},
		{
			"line": "\t[wheezy] - python3.2 <no-dsa> (minor issue)",
			"type": "package",
			"release": "wheezy",
			"package": "python3.2",
			"kind": "no-dsa",
			"description": "minor issue"
		},
		{
			"line": "\t- python3.3 <removed>",
			"type": "package",
			"package": "python3.3",
			"kind": "removed"
		},
		{
			"line": "\t- python3.4 3.4.0+20140417-1",
			"type": "package",
			"package": "python3.4",
			"kind": "fixed",
			"version": "3.4.0+20140417-1"
		},
		{
			"line": "\tNOTE: http://bugs.python.org/issue21529",
			"type": "NOTE",
			"description": "http://bugs.python.org/issue21529"
		}
	]
}
