{
	"header": {
		"line": "CVE-2017-16613 (An issue was discovered in middleware.py in OpenStack Swauth through 1 ...)",
		"name": "CVE-2017-16613",
		"description": "(An issue was discovered in middleware.py in OpenStack Swauth through 1 ...)"
	},
	"annotations": [
		{
			"line": "\t{DSA-4044-1}",
			"type": "xref",
			"bugs": [
				"DSA-4044-1"
			]
		},
		{
			"line": "\t- swauth 1.2.0-4 (bug #882314)",
			"type": "package",
			"package": "swauth",
			"kind": "fixed",
			"version": "1.2.0-4",
			"flags": [
				{
					"bug": 882314
				}
			]
		},
		{
			"line": "\tNOTE: https://bugs.launchpad.net/swift/+bug/1655781",
			"type": "NOTE",
			"description": "https://bugs.launchpad.net/swift/+bug/1655781"
		}
	]
}
