{
	"header": {
		"line": "CVE-2018-20102 (An out-of-bounds read in dns_validate_dns_response in dns.c was discov ...)",
		"name": "CVE-2018-20102",
		"description": "(An out-of-bounds read in dns_validate_dns_response in dns.c was discov ...)"
	},
	"annotations": [
		{
			"line": "\t{DLA-3034-1}",
			"type": "xref",
			"bugs": [
				"DLA-3034-1"
			]
		},
		{
			"line": "\t- haproxy 1.8.15-1 (bug #916308)",
			"type": "package",
			"package": "haproxy",
			"kind": "fixed",
			"version": "1.8.15-1",
			"flags": [
				{
					"bug": 916308
				}
			]
		},
		{
			"line": "\t[jessie] - haproxy <not-affected> (Vulnerable code not present)",
			"type": "package",
			"release": "jessie",
			"package": "haproxy",
			"kind": "not-affected",
			"description": "Vulnerable code not present"
		},
		{
			"line": "\tNOTE: http://git.haproxy.org/?p=haproxy.git;a=commit;h=efbbdf72992cd20458259962346044cafd9331c0",
			"type": "NOTE",
			"description": "http://git.haproxy.org/?p=haproxy.git;a=commit;h=efbbdf72992cd20458259962346044cafd9331c0"
		}
	]
}
