{
	"header": {
		"line": "CVE-2022-42969 (The py library through 1.11.0 for Python allows remote attackers to co ...)",
		"name": "CVE-2022-42969",
		"description": "(The py library through 1.11.0 for Python allows remote attackers to co ...)"
	},
	"annotations": [
		{
			"line": "\t- python-py <unfixed> (unimportant)",
			"type": "package",
			"package": "python-py",
			"kind": "unfixed",
			"flags": [
				{
					"severity": "unimportant"
				}
			]
		},
		{
			"line": "\tNOTE: https://github.com/pytest-dev/py/issues/287",
			"type": "NOTE",
			"description": "https://github.com/pytest-dev/py/issues/287"
		},
		{
			"line": "\tNOTE: Negligible security impact and disputed upstream",
			"type": "NOTE",
			"description": "Negligible security impact and disputed upstream"
		},
		{
			"line": "\tNOTE: https://github.com/pytest-dev/py/issues/287#issuecomment-1283784766",
			"type": "NOTE",
			"description": "https://github.com/pytest-dev/py/issues/287#issuecomment-1283784766"
		}
	]
}
