{
	"header": {
		"line": "CVE-2022-41767 (An issue was discovered in MediaWiki before 1.35.8, 1.36.x and 1.37.x  ...)",
		"name": "CVE-2022-41767",
		"description": "(An issue was discovered in MediaWiki before 1.35.8, 1.36.x and 1.37.x  ...)"
	},
	"annotations": [
		{
			"line": "\t{DSA-5246-1 DLA-3148-1}",
			"type": "xref",
			"bugs": [
				"DSA-5246-1",
				"DLA-3148-1"
			]
		},
		{
			"line": "\t- mediawiki 1:1.35.8-1",
			"type": "package",
			"package": "mediawiki",
			"kind": "fixed",
			"version": "1:1.35.8-1"
		},
		{
			"line": "\tNOTE: https://phabricator.wikimedia.org/T316304",
			"type": "NOTE",
			"description": "https://phabricator.wikimedia.org/T316304"
		},
		{
			"line": "\tNOTE: https://gerrit.wikimedia.org/r/c/mediawiki/core/+/836891",
			"type": "NOTE",
			"description": "https://gerrit.wikimedia.org/r/c/mediawiki/core/+/836891"
		}
	]
}
