{
	"header": {
		"line": "CVE-2020-21469 (An issue was discovered in PostgreSQL 12.2 allows attackers to cause a ...)",
		"name": "CVE-2020-21469",
		"description": "(An issue was discovered in PostgreSQL 12.2 allows attackers to cause a ...)"
	},
	"annotations": [
		{
			"line": "\t- postgresql-13 <not-affected> (Fixed before initial upload to Debian)",
			"type": "package",
			"package": "postgresql-13",
			"kind": "not-affected",
			"description": "Fixed before initial upload to Debian"
		},
		{
			"line": "\t- postgresql-11 <removed>",
			"type": "package",
			"package": "postgresql-11",
			"kind": "removed"
		},
		{
			"line": "\t[buster] - postgresql-11 11.10-0+deb10u1",
			"type": "package",
			"release": "buster",
			"package": "postgresql-11",
			"kind": "fixed",
			"version": "11.10-0+deb10u1"
		},
		{
			"line": "\tNOTE: https://www.postgresql.org/message-id/CAA8ZSMqAHDCgo07hqKoM5XJaoQy6Vv76O7966agez4ffyQktkA%40mail.gmail.com",
			"type": "NOTE",
			"description": "https://www.postgresql.org/message-id/CAA8ZSMqAHDCgo07hqKoM5XJaoQy6Vv76O7966agez4ffyQktkA%40mail.gmail.com"
		},
		{
			"line": "\tNOTE: Fixed by: https://github.com/postgres/postgres/commit/9abb2bfc046070b22e3be28173a0736da31cab5a (REL_13_BETA1)",
			"type": "NOTE",
			"description": "Fixed by: https://github.com/postgres/postgres/commit/9abb2bfc046070b22e3be28173a0736da31cab5a (REL_13_BETA1)"
		},
		{
			"line": "\tNOTE: Fixed by: https://github.com/postgres/postgres/commit/8b53dbada4a6a9e5f16548ca2c4d17cff55933d8 (REL_12_5)",
			"type": "NOTE",
			"description": "Fixed by: https://github.com/postgres/postgres/commit/8b53dbada4a6a9e5f16548ca2c4d17cff55933d8 (REL_12_5)"
		},
		{
			"line": "\tNOTE: Fixed by: https://github.com/postgres/postgres/commit/85834023a95e16d1d3fe73b0608e1608573753c3 (REL_11_10)",
			"type": "NOTE",
			"description": "Fixed by: https://github.com/postgres/postgres/commit/85834023a95e16d1d3fe73b0608e1608573753c3 (REL_11_10)"
		}
	]
}
