{
	"header": {
		"line": "CVE-2020-11810 (An issue was discovered in OpenVPN 2.4.x before 2.4.9. An attacker can ...)",
		"name": "CVE-2020-11810",
		"description": "(An issue was discovered in OpenVPN 2.4.x before 2.4.9. An attacker can ...)"
	},
	"annotations": [
		{
			"line": "\t{DLA-2992-1}",
			"type": "xref",
			"bugs": [
				"DLA-2992-1"
			]
		},
		{
			"line": "\t- openvpn 2.4.9-1 (low)",
			"type": "package",
			"package": "openvpn",
			"kind": "fixed",
			"version": "2.4.9-1",
			"flags": [
				{
					"severity": "low"
				}
			]
		},
		{
			"line": "\t[buster] - openvpn 2.4.7-1+deb10u1",
			"type": "package",
			"release": "buster",
			"package": "openvpn",
			"kind": "fixed",
			"version": "2.4.7-1+deb10u1"
		},
		{
			"line": "\t[jessie] - openvpn <not-affected> (Vulnerable code introduced in 2.4)",
			"type": "package",
			"release": "jessie",
			"package": "openvpn",
			"kind": "not-affected",
			"description": "Vulnerable code introduced in 2.4"
		},
		{
			"line": "\tNOTE: https://github.com/OpenVPN/openvpn/commit/37bc691e7d26ea4eb61a8a434ebd7a9ae76225ab",
			"type": "NOTE",
			"description": "https://github.com/OpenVPN/openvpn/commit/37bc691e7d26ea4eb61a8a434ebd7a9ae76225ab"
		}
	]
}
