{
	"header": {
		"line": "CVE-2020-25710 (A flaw was found in OpenLDAP in versions before 2.4.56. This flaw allo ...)",
		"name": "CVE-2020-25710",
		"description": "(A flaw was found in OpenLDAP in versions before 2.4.56. This flaw allo ...)"
	},
	"annotations": [
		{
			"line": "\t{DSA-4792-1 DLA-2481-1}",
			"type": "xref",
			"bugs": [
				"DSA-4792-1",
				"DLA-2481-1"
			]
		},
		{
			"line": "\t- openldap 2.4.56+dfsg-1",
			"type": "package",
			"package": "openldap",
			"kind": "fixed",
			"version": "2.4.56+dfsg-1"
		},
		{
			"line": "\tNOTE: https://bugs.openldap.org/show_bug.cgi?id=9384",
			"type": "NOTE",
			"description": "https://bugs.openldap.org/show_bug.cgi?id=9384"
		},
		{
			"line": "\tNOTE: https://git.openldap.org/openldap/openldap/-/commit/bdb0d459187522a6063df13871b82ba8dcc6efe2 (OPENLDAP_REL_ENG_2_4_56)",
			"type": "NOTE",
			"description": "https://git.openldap.org/openldap/openldap/-/commit/bdb0d459187522a6063df13871b82ba8dcc6efe2 (OPENLDAP_REL_ENG_2_4_56)"
		}
	]
}
