{
	"header": {
		"line": "CVE-2020-10735 (A flaw was found in python. In algorithms with quadratic time complexi ...)",
		"name": "CVE-2020-10735",
		"description": "(A flaw was found in python. In algorithms with quadratic time complexi ...)"
	},
	"annotations": [
		{
			"line": "\t{DLA-3966-1 DLA-3477-1}",
			"type": "xref",
			"bugs": [
				"DLA-3966-1",
				"DLA-3477-1"
			]
		},
		{
			"line": "\t- python3.11 3.11.0~rc2-1",
			"type": "package",
			"package": "python3.11",
			"kind": "fixed",
			"version": "3.11.0~rc2-1"
		},
		{
			"line": "\t- python3.10 3.10.7-1",
			"type": "package",
			"package": "python3.10",
			"kind": "fixed",
			"version": "3.10.7-1"
		},
		{
			"line": "\t- python3.9 <removed>",
			"type": "package",
			"package": "python3.9",
			"kind": "removed"
		},
		{
			"line": "\t- python3.7 <removed>",
			"type": "package",
			"package": "python3.7",
			"kind": "removed"
		},
		{
			"line": "\t- python2.7 <removed>",
			"type": "package",
			"package": "python2.7",
			"kind": "removed"
		},
		{
			"line": "\t[bullseye] - python2.7 <ignored> (Unsupported in Bullseye, only included to build a few applications)",
			"type": "package",
			"release": "bullseye",
			"package": "python2.7",
			"kind": "ignored",
			"description": "Unsupported in Bullseye, only included to build a few applications"
		},
		{
			"line": "\t[buster] - python2.7 <ignored> (Minor issue, CPU DoS, intrusive backport)",
			"type": "package",
			"release": "buster",
			"package": "python2.7",
			"kind": "ignored",
			"description": "Minor issue, CPU DoS, intrusive backport"
		},
		{
			"line": "\t- pypy3 7.3.10+dfsg-1",
			"type": "package",
			"package": "pypy3",
			"kind": "fixed",
			"version": "7.3.10+dfsg-1"
		},
		{
			"line": "\t[buster] - pypy3 <no-dsa> (Minor issue)",
			"type": "package",
			"release": "buster",
			"package": "pypy3",
			"kind": "no-dsa",
			"description": "Minor issue"
		},
		{
			"line": "\tNOTE: https://github.com/python/cpython/issues/95778",
			"type": "NOTE",
			"description": "https://github.com/python/cpython/issues/95778"
		},
		{
			"line": "\tNOTE: https://github.com/python/cpython/pull/96499",
			"type": "NOTE",
			"description": "https://github.com/python/cpython/pull/96499"
		},
		{
			"line": "\tNOTE: https://github.com/python/cpython/commit/f8b71da9aac6ea74808dcdd0cc266e705431356b (v3.11.0rc2)",
			"type": "NOTE",
			"description": "https://github.com/python/cpython/commit/f8b71da9aac6ea74808dcdd0cc266e705431356b (v3.11.0rc2)"
		},
		{
			"line": "\tNOTE: https://github.com/python/cpython/commit/8f0fa4bd10aba723aff988720cd26b93be99bc12 (v3.10.7)",
			"type": "NOTE",
			"description": "https://github.com/python/cpython/commit/8f0fa4bd10aba723aff988720cd26b93be99bc12 (v3.10.7)"
		},
		{
			"line": "\tNOTE: https://github.com/python/cpython/commit/cec1e9dfd769bd3a16142d0fdd1a36f19c77ed15 (v3.9.14)",
			"type": "NOTE",
			"description": "https://github.com/python/cpython/commit/cec1e9dfd769bd3a16142d0fdd1a36f19c77ed15 (v3.9.14)"
		},
		{
			"line": "\tNOTE: https://github.com/python/cpython/commit/15ec1afd4fcd2da1e2d2b256c562fb42d8d886a2 (v3.7.14)",
			"type": "NOTE",
			"description": "https://github.com/python/cpython/commit/15ec1afd4fcd2da1e2d2b256c562fb42d8d886a2 (v3.7.14)"
		}
	]
}
